### ISSUE TITLE
Observaciones y correcciones 

### ISSUE THREAD

**Issue by dovirojas** [fralfaro/python_intro2#1]
-El apartado 4.2.1 hacia el 4.2.4 parece no estar corriendo, no me aparece el print cuando se corre el código. Probado en Brave y Firefox
-En el apartado 4.3.7 el primer y segundo print son el mismo

**Comment by fralfaro** [comment]
- **Apartado 4.2.1 - 4.2.4**: Se ha modificado el manejo de los `type`, reemplazándolos por `print` para simplificar la visualización. No obstante, aún estamos investigando cómo utilizar el comando `type` efectivamente con Pyodide.
- **Apartado 4.3.7**:  Listo!
